### ISSUE TITLE
Start building the AMI

### ISSUE THREAD

**Issue by chmanie** [cloudrig/CloudRIG-AWS-AMI#1]
Here are some very helpful notes:

https://github.com/david-cao/pi-stream/blob/master/AWSsetup.md

And here are some suggestions for building the actual image:

https://github.com/cloudrig/CloudRIG/issues/10#issuecomment-535703128

I can dig into this a bit once I’ve got some free time.

**Comment by NitriKx** [comment]
Hello ! 

Thanks for the links. I've also got some tricks from https://github.com/putty182/gcloudrig/.
The AMI is nearly finished I'm testing it for the moment but it will be available in all regions soon.
