### ISSUE TITLE
Can not run the Parsec Preparation script with SSM

### ISSUE THREAD

**Issue by NitriKx** [cloudrig/CloudRIG-AWS-AMI#2]
As SSM is running with `NT AUTHORITY\SYSTEM` I can not run scripts as another user :/ 
Which is mandatory as the preparation script manipulate the registry and use some user-specific paths

**Comment by NitriKx** [comment]
UAC seems to be the cause

**Comment by sandstrom** [comment]
Support for parsec would be great! Rainway doesn't work on macOS.

There are some related scripts here:
https://github.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool

**Comment by NitriKx** [comment]
There is no macOS version but the web version is working nice (and you can make a desktop simili-app with Chrome).
But yes I will also add parsec.

**Comment by andrewmd5** [comment]
Just FYI you can install Rainway from Chrome as a Progressive Web App  https://rainway.com/blog/2020/05/12/heres-whats-new-in-the-may-update/

**Comment by dropitlikecross** [comment]
Parsec also benchmarks a lot better than rainway, why not just add the option for both and you can select during setup?

**Comment by NitriKx** [comment]
I’m going to install both of them in the AMI. 

The thing is that those tools do not allow to register the instance via an API key. As a workaround the user needs to connect through VNC and log in in his favorite streaming client. 

We could also imagine to develop something that is going to automatically fill the login form in the app with the user credentials (and support giving the MFA token when requested by the app).

**Comment by NitriKx** [comment]
I've also replaced VNC with NICE DCV app. 
This one seems that a good performances also but I've not tried it yet on intensive games.
