### ISSUE TITLE
Build scripts reference S3 bucket that is not publically accessible

### ISSUE THREAD

**Issue by ryanelliottsmith** [cloudrig/CloudRIG-AWS-AMI#8]
GPUPreperation.psm1 and UtilsAppInstaller.psm1 both seem to have heavy dependencies on cloudrig-amifactory, which isn't publically accessible.

Some of this looks like it could be replaced with chocolatey, so I'll play around with that.

**Comment by NitriKx** [comment]
Hello ! 
Sorry for the (very) late reply. 
I've made the bucket public (with Requester Pays enabled). 
Benoît
